CREATE TABLE IF NOT EXISTS [groups](
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name CHAR(6) UNIQUE
);

CREATE TABLE IF NOT EXISTS teachers(
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	fullname VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS students(
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	fullname VARCHAR(100),
	group_id REFERENCES [groups] (id)
);

CREATE TABLE IF NOT EXISTS subjects(
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name VARCHAR(255),
	teacher_id REFERENCES teachers (id)
);

CREATE TABLE IF NOT EXISTS grades(
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	subject_id REFERENCES subjects (id),
	student_id REFERENCES students (id),
	grade INTEGER,
	date_of DATE
);